export type ShiftType = 'Day' | 'Night' | 'Rest' | '-';
export type WorkStatus = 'Prod.' | 'Jail' | 'DailyProduction';
export type Role = 'TC.L1' | 'TC.L2' | 'TC.L3' | 'Hall Asist' | 'Infeeder' | 'Sr.Infeeder' | 'Ops.L1';
export type ShiftTeam = 'Green' | 'Blue' | 'Orange' | 'Yellow';

export interface ShiftEntry {
  day: string;
  night: string;
  dayAutoGenerated?: boolean;
  nightAutoGenerated?: boolean;
}

export interface Employee {
  id: string;
  name: string;
  role: Role;
  indirectDirect: 'Direct' | 'Indirect';
  status: WorkStatus;
  shiftTeam: ShiftTeam;
  gender: 'Male' | 'Female';
  shifts: Record<string, ShiftEntry>;
}

export interface Adjustment {
  id: string;
  employeeId: string;
  name: string;
  role?: string;
  shiftTeam?: string;
  gender?: string;
  hours: number;
  date: string;
  isNight?: boolean;
  reason: string;
  comments: string;
  // New fields from reference
  type?: string;
  duration?: string;
  shift?: string;
  notes?: string;
  indirectDirect?: 'Direct' | 'Indirect';
  workStatus?: WorkStatus;
}

export interface AssemblyLine {
  id: string;
  name: string;
  capacity: number;
  currentWorkers: number;
  assignedWorkers: WorkerAssignment[];
}

export interface WorkerAssignment {
  employeeId: string;
  name: string;
  initials: string;
  experienceCount: number; // Number of shifts on this line
}
